server:
  port: 8095  # Server Port

#Spring
# Mysql settings
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver   # driver
    url: jdbc:mysql://localhost:3306/springdb     # DB URL
    username: root                                # user vfvvmbnkmm
    password: 1234                                # password

  # JPA settings
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update                           # DDL create,drop,update
    properties:
      hibernate:
        show_sql: true                               # SQL show?
        format_sql: true                             # SQL format

  #Thymeleaf settings
  thymeleaf:
    prefix: classpath:templates/     # view
    suffix: .html                    # view( thymeleaf)
    cache: false

  #spring:
  profiles:
    include: oauth2  # application-oauth2.yml


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace